window.esdocSearchIndex = [
  [
    "ttuacm-website/ttuacm_website/controllers/event.controller.js~addattendee",
    "function/index.html#static-function-addAttendee",
    "<span>addAttendee</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/event.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~confirmtoken",
    "function/index.html#static-function-confirmToken",
    "<span>confirmToken</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~contactus",
    "function/index.html#static-function-contactUs",
    "<span>contactUs</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/event.controller.js~createcalendar",
    "function/index.html#static-function-createCalendar",
    "<span>createCalendar</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/event.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~forgotlogin",
    "function/index.html#static-function-forgotLogin",
    "<span>forgotLogin</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~generatejwttoken",
    "function/index.html#static-function-generateJWTToken",
    "<span>generateJWTToken</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/event.controller.js~getattendees",
    "function/index.html#static-function-getAttendees",
    "<span>getAttendees</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/event.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~getprofile",
    "function/index.html#static-function-getProfile",
    "<span>getProfile</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/event.controller.js~getrawevents",
    "function/index.html#static-function-getRawEvents",
    "<span>getRawEvents</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/event.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/event.controller.js~listevents",
    "function/index.html#static-function-listEvents",
    "<span>listEvents</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/event.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~login",
    "function/index.html#static-function-login",
    "<span>login</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/routes/event.router.js~membersonlyroute",
    "variable/index.html#static-variable-membersOnlyRoute",
    "<span>membersOnlyRoute</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/routes/event.router.js</span>",
    "variable"
  ],
  [
    "ttuacm-website/ttuacm_website/routes/utils.js~membersonlyroute",
    "variable/index.html#static-variable-membersOnlyRoute",
    "<span>membersOnlyRoute</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/routes/utils.js</span>",
    "variable"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/auth.controller.js~oauth2",
    "function/index.html#static-function-oauth2",
    "<span>oauth2</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/auth.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~register",
    "function/index.html#static-function-register",
    "<span>register</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/event.controller.js~removeattendee",
    "function/index.html#static-function-removeAttendee",
    "<span>removeAttendee</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/event.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~resetpassword",
    "function/index.html#static-function-resetPassword",
    "<span>resetPassword</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~resettoken",
    "function/index.html#static-function-resetToken",
    "<span>resetToken</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~sendchangedpasswordemail",
    "function/index.html#static-function-sendChangedPasswordEmail",
    "<span>sendChangedPasswordEmail</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~sendconfirmationemail",
    "function/index.html#static-function-sendConfirmationEmail",
    "<span>sendConfirmationEmail</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~sendresetemail",
    "function/index.html#static-function-sendResetEmail",
    "<span>sendResetEmail</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/event.controller.js~updateattendee",
    "function/index.html#static-function-updateAttendee",
    "<span>updateAttendee</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/event.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~updateresume",
    "function/index.html#static-function-updateResume",
    "<span>updateResume</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~updateuser",
    "function/index.html#static-function-updateUser",
    "<span>updateUser</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "ttuacm-website/ttuacm_website/controllers/user.controller.js~verifyuser",
    "function/index.html#static-function-verifyUser",
    "<span>verifyUser</span> <span class=\"search-result-import-path\">ttuacm-website/TTUACM_Website/controllers/user.controller.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "ttuacm_website/controllers/auth.controller.js",
    "file/TTUACM_Website/controllers/auth.controller.js.html",
    "TTUACM_Website/controllers/auth.controller.js",
    "file"
  ],
  [
    "ttuacm_website/controllers/contacts.controller.js",
    "file/TTUACM_Website/controllers/contacts.controller.js.html",
    "TTUACM_Website/controllers/contacts.controller.js",
    "file"
  ],
  [
    "ttuacm_website/controllers/event.controller.js",
    "file/TTUACM_Website/controllers/event.controller.js.html",
    "TTUACM_Website/controllers/event.controller.js",
    "file"
  ],
  [
    "ttuacm_website/controllers/user.controller.js",
    "file/TTUACM_Website/controllers/user.controller.js.html",
    "TTUACM_Website/controllers/user.controller.js",
    "file"
  ],
  [
    "ttuacm_website/routes/auth.router.js",
    "file/TTUACM_Website/routes/auth.router.js.html",
    "TTUACM_Website/routes/auth.router.js",
    "file"
  ],
  [
    "ttuacm_website/routes/contacts.router.js",
    "file/TTUACM_Website/routes/contacts.router.js.html",
    "TTUACM_Website/routes/contacts.router.js",
    "file"
  ],
  [
    "ttuacm_website/routes/event.router.js",
    "file/TTUACM_Website/routes/event.router.js.html",
    "TTUACM_Website/routes/event.router.js",
    "file"
  ],
  [
    "ttuacm_website/routes/event.router.js~eventsrouter-addattendee",
    "typedef/index.html#static-typedef-EventsRouter-addAttendee",
    "TTUACM_Website/routes/event.router.js~EventsRouter-addAttendee",
    "typedef"
  ],
  [
    "ttuacm_website/routes/event.router.js~eventsrouter-getattendees",
    "typedef/index.html#static-typedef-EventsRouter-getAttendees",
    "TTUACM_Website/routes/event.router.js~EventsRouter-getAttendees",
    "typedef"
  ],
  [
    "ttuacm_website/routes/event.router.js~eventsrouter-getrawevents",
    "typedef/index.html#static-typedef-EventsRouter-getRawEvents",
    "TTUACM_Website/routes/event.router.js~EventsRouter-getRawEvents",
    "typedef"
  ],
  [
    "ttuacm_website/routes/event.router.js~eventsrouter-listevents",
    "typedef/index.html#static-typedef-EventsRouter-listEvents",
    "TTUACM_Website/routes/event.router.js~EventsRouter-listEvents",
    "typedef"
  ],
  [
    "ttuacm_website/routes/event.router.js~eventsrouter-removeattendee",
    "typedef/index.html#static-typedef-EventsRouter-removeAttendee",
    "TTUACM_Website/routes/event.router.js~EventsRouter-removeAttendee",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js",
    "file/TTUACM_Website/routes/user.router.js.html",
    "TTUACM_Website/routes/user.router.js",
    "file"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-confirmtoken",
    "typedef/index.html#static-typedef-UserRouter-confirmToken",
    "TTUACM_Website/routes/user.router.js~UserRouter-confirmToken",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-contactus",
    "typedef/index.html#static-typedef-UserRouter-contactUs",
    "TTUACM_Website/routes/user.router.js~UserRouter-contactUs",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-forgotlogin",
    "typedef/index.html#static-typedef-UserRouter-forgotLogin",
    "TTUACM_Website/routes/user.router.js~UserRouter-forgotLogin",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-getprofile",
    "typedef/index.html#static-typedef-UserRouter-getProfile",
    "TTUACM_Website/routes/user.router.js~UserRouter-getProfile",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-login",
    "typedef/index.html#static-typedef-UserRouter-login",
    "TTUACM_Website/routes/user.router.js~UserRouter-login",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-register",
    "typedef/index.html#static-typedef-UserRouter-register",
    "TTUACM_Website/routes/user.router.js~UserRouter-register",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-register",
    "typedef/index.html#static-typedef-UserRouter-register",
    "TTUACM_Website/routes/user.router.js~UserRouter-register",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-resetpassword",
    "typedef/index.html#static-typedef-UserRouter-resetPassword",
    "TTUACM_Website/routes/user.router.js~UserRouter-resetPassword",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-resettoken",
    "typedef/index.html#static-typedef-UserRouter-resetToken",
    "TTUACM_Website/routes/user.router.js~UserRouter-resetToken",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-sendconfirmationemail",
    "typedef/index.html#static-typedef-UserRouter-sendConfirmationEmail",
    "TTUACM_Website/routes/user.router.js~UserRouter-sendConfirmationEmail",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-updateresume",
    "typedef/index.html#static-typedef-UserRouter-updateResume",
    "TTUACM_Website/routes/user.router.js~UserRouter-updateResume",
    "typedef"
  ],
  [
    "ttuacm_website/routes/user.router.js~userrouter-updateuser",
    "typedef/index.html#static-typedef-UserRouter-updateUser",
    "TTUACM_Website/routes/user.router.js~UserRouter-updateUser",
    "typedef"
  ],
  [
    "ttuacm_website/routes/utils.js",
    "file/TTUACM_Website/routes/utils.js.html",
    "TTUACM_Website/routes/utils.js",
    "file"
  ]
]